update icon : appwrite
konpa/devicon pull request #2196
Opened 2024-05-23 16:04 UTC by Yashh56

Close #2181

2024-06-07 12:52 UTC, Yashh56 commented
**Hey Maintainer Please Review this PR**

2024-06-07 15:00 UTC, Snailedlt requested changes, later dismissed
Thank you for the contribution!

The wordmark versions look very good!

The non-wordmark versions are distorted. Please make sure to keep the aspect ratios the same when resizing the icons, so that they don't become distorted.

2024-06-07 15:00 UTC, Snailedlt commented on icons/appwrite/appwrite-original.svg
Looks like this icon has been distorted.

2024-06-07 15:00 UTC, Snailedlt commented on icons/appwrite/appwrite-plain.svg
Same here :)

2024-06-07 16:52 UTC, Yashh56 commented
**Thanks @Snailedlt  for reviewing this PR Can you tell me how to resolve this issue ?**

2024-06-07 17:50 UTC, Snailedlt commented
> **Thanks @Snailedlt  for reviewing this PR Can you tell me how to resolve this issue ?**

@Yashh56 I think the easiest way is downloading the official icons again and making sure that the aspect ratio is maintained when you resize it :)

If you're using inkscape you can follow this guide when resizing: https://github.com/devicons/devicon/issues/1306#issuecomment-1296051881

2024-06-10 10:51 UTC, Yashh56 commented
Hey @Snailedlt are these changes fine?

2024-06-15 14:58 UTC, Yashh56 commented
**Hey Maintainer Please Review this PR**

2024-06-17 07:57 UTC, weh requested changes, later dismissed
It looks like the changes requested by @Snailedlt are still not resolved.
The `original` and `plain` version are still squished, and not round anymore.

![squished](https://github.com/devicons/devicon/assets/482423/520d9bd9-1d07-4a84-95cf-e1117d6fc3b1)

2024-06-17 07:59 UTC, weh commented
...also `original` and `plain` could be aliased since it is only a single color (?)

2024-06-17 08:32 UTC, weh commented
And i forgot also that the original and plain should not have that much spacing around the icon. 
So to summarize again:

- Fix the squished aspect ratio
- Remove the spacing around the Icon
- Remove the `plain-wordmark` / `original-wordmark` alias

```json
        "aliases": [
            {
                "base": "plain",
                "alias": "original"
            }
        ]
```

2024-06-17 11:11 UTC, Snailedlt commented
Refer to guides under [this issue](https://github.com/devicons/devicon/issues/1306) as well as the [wiki](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons) if you're unsure how to fix the issues :)

2024-06-17 11:24 UTC, Yashh56 commented
**how can i squished aspect ratio ?**

2024-06-17 11:25 UTC, Yashh56 commented
**I used Resize to resize the aspect ratio**

2024-06-17 11:51 UTC, Snailedlt commented
@Yashh56 If you're using inkscape, make sure you check the box to scale proportionally
![image](https://github.com/devicons/devicon/assets/43886029/6a19031e-899f-4643-8bd3-6bfd4cb53aa6)
Otherwise the svg will get stretched to fit the viewbox.

Here's two different guides to resize to a square. Both can be found as comments in [the issue I linked to earlier](https://github.com/devicons/devicon/issues/1306):
- https://github.com/devicons/devicon/pull/1938#discussion_r1378205483
- https://github.com/devicons/devicon/pull/1465#issuecomment-1287950577

2024-10-24 18:18 UTC, Yashh56 commented
**Hey Maintainer Please review the current changes. **

2024-10-26 03:24 UTC, Yashh56 commented
**Hey @Snailedlt, Can you review my changes :)**

2024-12-23 02:07 UTC, canaleal approved these changes
Ive optimized the svgs using this [tutorial](https://github.com/devicons/devicon/wiki/Optimizing-icons) and made sure there were no artifacts in icomoon. 

The eps file can be removed as it's not needed anymore and because the original icon is simple enough to be used as the plain icon, the plain svg was removed and replaced with an alias. 

![image](https://github.com/user-attachments/assets/15aae182-fd5f-4cd8-b15c-593620151986)

2024-12-23 02:17 UTC, merged